### ISSUE TITLE
Unable to build bfx-hf-ui (SEP 26 16:16 utc)

### ISSUE THREAD

**Issue by pointops** [bitfinexcom/bfx-hf-ui-core#101]
>username@Anglia:~$ cd bfx-hf-ui
>username@Anglia:~/bfx-hf-ui$ npm run build

> bfx-hf-ui@3.18.0 build /home/username/bfx-hf-ui
> npm run fetch-core && npm run update-core && npm run preinstall && cd bfx-hf-ui-core && cross-env GENERATE_SOURCEMAP=false npm run build-css && cross-env REACT_APP_WSS_URL=ws://localhost:45000 REACT_APP_DS_URL=ws://localhost:23521 REACT_APP_UFX_PUBLIC_API_URL=http://localhost:45001 REACT_APP_IS_ELECTRON_APP=true node scripts/build.js

> bfx-hf-ui@3.18.0 fetch-core /home/username/bfx-hf-ui
> git submodule update --init --recursive

> bfx-hf-ui@3.18.0 update-core /home/username/bfx-hf-ui
> git submodule update --remote --merge

**Updating cdefb70..8c5ccf2
error: Your local changes to the following files would be overwritten by merge:
        package-lock.json
Please commit your changes or stash them before you merge.
Aborting
Unable to merge '8c5ccf2f7fa0566e41c3ea1ae1ddfe136bf02e90' in submodule path 'bfx-hf-ui-core'**
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! bfx-hf-ui@3.18.0 update-core: `git submodule update --remote --merge`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the bfx-hf-ui@3.18.0 update-core script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/username/.npm/_logs/2021-09-26T15_54_58_425Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! bfx-hf-ui@3.18.0 build: `npm run fetch-core && npm run update-core && npm run preinstall && cd bfx-hf-ui-core && cross-env GENERATE_SOURCEMAP=false npm run build-css && cross-env REACT_APP_WSS_URL=ws://localhost:45000 REACT_APP_DS_URL=ws://localhost:23521 REACT_APP_UFX_PUBLIC_API_URL=http://localhost:45001 REACT_APP_IS_ELECTRON_APP=true node scripts/build.js`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the bfx-hf-ui@3.18.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/username/.npm/_logs/2021-09-26T15_54_58_449Z-debug.log
username@Anglia:~/bfx-hf-ui$

**Comment by Blaumaus** [comment]
Can you run `git restore package-lock.json` in the project's root and try to build this again?

**Comment by pointops** [comment]
> git restore package-lock.json
git: 'restore' is not a git command. See 'git --help'.

> git --version
git version 2.20.1

> sudo apt install git
git is already the newest version (1:2.20.1-2+deb10u3)

**Comment by pointops** [comment]
Could it be the latest https://github.com/bitfinexcom/bfx-hf-ui-core 

![obrazek](https://user-images.githubusercontent.com/80652610/134863039-a27a39cd-6f57-4ade-9bbf-a60cc82d69e7.png)

is not propagated into the main project well?

![obrazek](https://user-images.githubusercontent.com/80652610/134863221-599b48c9-477b-426e-b4b4-b3757e5a299f.png)

https://github.com/bitfinexcom/bfx-hf-ui

**Comment by pointops** [comment]
> Can you run `git restore package-lock.json` in the project's root and try to build this again?

Tried on a clean install [Ubuntu 20.04 LTS repository have Git 2.25]
**wsl2 Ubuntu 20.04 LTS**

>cd ~
sudo apt update
sudo apt upgrade -y
sudo apt autoremove

>sudo apt install git -y
sudo apt install curl -y
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash

close / restart terminal 

>nvm install --lts
git clone https://github.com/bitfinexcom/bfx-hf-ui
cd bfx-hf-ui
npm run fetch-core
npm install
npm run build

>git restore package-lock.json
npm run build

No improvement.

**Comment by Blaumaus** [comment]
> 
> 
> > Can you run `git restore package-lock.json` in the project's root and try to build this again?
> 
> Tried on a clean install [Ubuntu 20.04 LTS repository have Git 2.25 with 'restore'] **wsl2 Ubuntu 20.04 LTS**
> 
> > cd ~
> > sudo apt update
> > sudo apt upgrade -y
> > sudo apt autoremove
> 
> > sudo apt install git -y
> > sudo apt install curl -y
> > curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
> 
> close / restart terminal
> 
> > nvm install --lts
> > git clone https://github.com/bitfinexcom/bfx-hf-ui
> > cd bfx-hf-ui
> > npm run fetch-core
> > npm install
> > npm run build
> 
> > git restore package-lock.json
> > npm run build
> 
> No improvement.
> 
> ![obrazek](https://user-images.githubusercontent.com/80652610/134866433-2b7df3d4-9cab-4044-a120-704d9f502bb8.png)

Sorry, I meant:
```bash
cd ./bfx-hf-ui-core
git restore package-lock.json
```

or if you're using an outdated Git version, you might try:

```bash
cd ./bfx-hf-ui-core
git checkout -- .
```

and after that do a `npm run build` in the `bfx-hf-ui` directory.

**Comment by pointops** [comment]
That worked. Thanks.
